#!/usr/bin/env bash

function init() {
  echo "Initing dir for $1"

  mkdir domains
  mkdir downloads
  mkdir github
  mkdir notes

  echo "$1 bounty program." > ./notes/README.md

  git init
  git commit -am "Initial commit for $1"
  echo "Please setup your git remote."
  echo "Done"
}

if [ -z "$1" ]; then #no arguments provided
  echo "Bounty name needed."
else
  init $1
fi

